(function () {
    var myapp = angular.module('app', ['ui.router'
        , 'ngResource'
        , 'ngCookies'
        , 'ui.bootstrap'
        , 'mgo-angular-wizard'        
        , 'campaign'
        , 'ngDroplet'
        , 'textAngular'
        , 'simditor'
        , 'ngSanitize'
        , 'ui.bootstrap.datetimepicker'
        , 'colorpicker.module'
        , 'profile'
        , 'blockUI'
        , 'ngMap'
        , 'angular-flexslider'
        ,'checklist-model'
        ,'analytic'
       ,'subscriptionLayout'
       ,'codeImplementation'
       ,'upgradePlan'
    //    ,'rzModule'
       ,'ya.nouislider'
    ]);
})();